export const armors = [
  { name: "Albino Plate", icon: "Albino Plate", imbuingSlots: 2 },
  { name: "Amazon Armor", icon: "Amazon Armor", imbuingSlots: 2 },
  { name: "Arcane Dragon Robe", icon: "Arcane Dragon Robe", imbuingSlots: 1 },
  { name: "Bear Skin", icon: "Bear Skin", imbuingSlots: 1 },
  { name: "Blue Robe", icon: "Blue Robe", imbuingSlots: 2 },
  { name: "Chain Armor", icon: "Chain Armor", imbuingSlots: 2 },
  { name: "Crown Armor", icon: "Crown Armor", imbuingSlots: 1 },
  {
    name: "Dauntless Dragon Scale Armor",
    icon: "Dauntless Dragon Scale Armor",
    imbuingSlots: 2,
  },
  { name: "Dawnfire Sherwani", icon: "Dawnfire Sherwani", imbuingSlots: 1 },
  { name: "Death Oyoroi", icon: "Death Oyoroi", imbuingSlots: 1 },
  { name: "Demon Armor", icon: "Demon Armor", imbuingSlots: 2 },
  { name: "Depth Lorica", icon: "Depth Lorica", imbuingSlots: 2 },
  { name: "Dragon Scale Mail", icon: "Dragon Scale Mail", imbuingSlots: 1 },
  { name: "Dream Shroud", icon: "Dream Shroud", imbuingSlots: 1 },
  { name: "Dwarven Armor", icon: "Dwarven Armor", imbuingSlots: 2 },
  { name: "Eldritch Cuirass", icon: "Eldritch Cuirass", imbuingSlots: 2 },
  { name: "Elite Draken Mail", icon: "Elite Draken Mail", imbuingSlots: 2 },
  { name: "Elven Mail", icon: "Elven Mail", imbuingSlots: 3 },
  { name: "Embrace of Nature", icon: "Embrace of Nature", imbuingSlots: 1 },
  { name: "Falcon Plate", icon: "Falcon Plate", imbuingSlots: 2 },
  { name: "Ghost Chestplate", icon: "Ghost Chestplate", imbuingSlots: 2 },
  { name: "Gnome Armor", icon: "Gnome Armor", imbuingSlots: 2 },
  { name: "Gnomish Cuirass", icon: "Gnomish Cuirass", imbuingSlots: 1 },
  { name: "Golden Armor", icon: "Golden Armor", imbuingSlots: 2 },
  { name: "Green Demon Armor", icon: "Green Demon Armor", imbuingSlots: 2 },
  { name: "Heat Core", icon: "Heat Core", imbuingSlots: 2 },
  { name: "Heavy Metal T-Shirt", icon: "Heavy Metal T-Shirt", imbuingSlots: 2 },
  { name: "Knight Armor", icon: "Knight Armor", imbuingSlots: 2 },
  { name: "Leopard Armor", icon: "Leopard Armor", imbuingSlots: 2 },
  { name: "Lion Plate", icon: "Lion Plate", imbuingSlots: 2 },
  { name: "Living Armor", icon: "Living Armor", imbuingSlots: 1 },
  { name: "Magic Plate Armor", icon: "Magic Plate Armor", imbuingSlots: 2 },
  { name: "Mammoth Fur Cape", icon: "Mammoth Fur Cape", imbuingSlots: 2 },
  {
    name: "Master Archer's Armor",
    icon: "Master Archer's Armor",
    imbuingSlots: 1,
  },
  { name: "Merudri Battle Mail", icon: "Merudri Battle Mail", imbuingSlots: 2 },
  { name: "Merudri Nanbando", icon: "Merudri Nanbando", imbuingSlots: 1 },
  { name: "Midnight Tunic", icon: "Midnight Tunic", imbuingSlots: 1 },
  { name: "Mooh'tah Plate", icon: "Mooh'tah Plate", imbuingSlots: 2 },
  { name: "Mutated Skin Armor", icon: "Mutated Skin Armor", imbuingSlots: 2 },
  {
    name: "Mystical Dragon Robe",
    icon: "Mystical Dragon Robe",
    imbuingSlots: 1,
  },
  { name: "Naga Tanko", icon: "Naga Tanko", imbuingSlots: 2 },
  { name: "Noble Armor", icon: "Noble Armor", imbuingSlots: 2 },
  { name: "Ornate Chestplate", icon: "Ornate Chestplate", imbuingSlots: 2 },
  { name: "Paladin Armor", icon: "Paladin Armor", imbuingSlots: 1 },
  { name: "Prismatic Armor", icon: "Prismatic Armor", imbuingSlots: 1 },
  {
    name: "Robe of Enlightenment",
    icon: "Robe of Enlightenment",
    imbuingSlots: 1,
  },
  { name: "Soulgarb", icon: "Soulgarb", imbuingSlots: 2 },
  { name: "Soulmantle", icon: "Soulmantle", imbuingSlots: 2 },
  { name: "Soulshell", icon: "Soulshell", imbuingSlots: 2 },
  { name: "Soulshroud", icon: "Soulshroud", imbuingSlots: 2 },
  { name: "Spiritthorn Armor", icon: "Spiritthorn Armor", imbuingSlots: 2 },
  {
    name: "Stoic Iks Chestplate",
    icon: "Stoic Iks Chestplate",
    imbuingSlots: 2,
  },
  { name: "Stoic Iks Cuirass", icon: "Stoic Iks Cuirass", imbuingSlots: 1 },
  { name: "Stoic Iks Robe", icon: "Stoic Iks Robe", imbuingSlots: 2 },
  { name: "Toga Mortis", icon: "Toga Mortis", imbuingSlots: 1 },
  {
    name: "Unerring Dragon Scale Armor",
    icon: "Unerring Dragon Scale Armor",
    imbuingSlots: 2,
  },
];
