export const axes = [
  { name: "Amber Axe", icon: "Amber Axe", imbuingSlots: 2 },
  { name: "Amber Greataxe", icon: "Amber Greataxe", imbuingSlots: 2 },
  { name: "Axe of Carving", icon: "Axe of Carving", imbuingSlots: 3 },
  { name: "Axe of Destruction", icon: "Axe of Destruction", imbuingSlots: 2 },
  { name: "Axe of Mayhem", icon: "Axe of Mayhem", imbuingSlots: 3 },
  { name: "Axe of Remedy", icon: "Axe of Remedy", imbuingSlots: 3 },
  { name: "Barbarian Axe", icon: "Barbarian Axe", imbuingSlots: 2 },
  { name: "Beastslayer Axe", icon: "Beastslayer Axe", imbuingSlots: 2 },
  { name: "Butcher's Axe", icon: "Butcher's Axe", imbuingSlots: 2 },
  { name: "Chopper of Carving", icon: "Chopper of Carving", imbuingSlots: 3 },
  {
    name: "Chopper of Destruction",
    icon: "Chopper of Destruction",
    imbuingSlots: 3,
  },
  { name: "Chopper of Mayhem", icon: "Chopper of Mayhem", imbuingSlots: 3 },
  { name: "Chopper of Remedy", icon: "Chopper of Remedy", imbuingSlots: 3 },
  { name: "Cobra Axe", icon: "Cobra Axe", imbuingSlots: 2 },
  { name: "Crystalline Axe", icon: "Crystalline Axe", imbuingSlots: 1 },
  { name: "Demonwing Axe", icon: "Demonwing Axe", imbuingSlots: 2 },
  { name: "Dragon Lance", icon: "Dragon Lance", imbuingSlots: 3 },
  {
    name: "Draining Inferniarch Battleaxe",
    icon: "Draining Inferniarch Battleaxe",
    imbuingSlots: 1,
  },
  {
    name: "Draining Inferniarch Greataxe",
    icon: "Draining Inferniarch Greataxe",
    imbuingSlots: 1,
  },
  { name: "Drakinata", icon: "Drakinata", imbuingSlots: 3 },
  { name: "Dreaded Cleaver", icon: "Dreaded Cleaver", imbuingSlots: 2 },
  { name: "Dwarven Axe", icon: "Dwarven Axe", imbuingSlots: 2 },
  { name: "Eldritch Greataxe", icon: "Eldritch Greataxe", imbuingSlots: 2 },
  { name: "Executioner", icon: "Executioner", imbuingSlots: 2 },
  { name: "Falcon Battleaxe", icon: "Falcon Battleaxe", imbuingSlots: 2 },
  {
    name: "Gilded Eldritch Greataxe",
    icon: "Gilded Eldritch Greataxe",
    imbuingSlots: 2,
  },
  {
    name: "Grand Sanguine Battleaxe",
    icon: "Grand Sanguine Battleaxe",
    imbuingSlots: 3,
  },
  {
    name: "Grand Sanguine Hatchet",
    icon: "Grand Sanguine Hatchet",
    imbuingSlots: 2,
  },
  { name: "Great Axe", icon: "Great Axe", imbuingSlots: 2 },
  { name: "Guardian Halberd", icon: "Guardian Halberd", imbuingSlots: 3 },
  { name: "Headchopper", icon: "Headchopper", imbuingSlots: 3 },
  { name: "Hellforged Axe", icon: "Hellforged Axe", imbuingSlots: 1 },
  { name: "Heroic Axe", icon: "Heroic Axe", imbuingSlots: 2 },
  { name: "Hive Scythe", icon: "Hive Scythe", imbuingSlots: 2 },
  { name: "Impaler", icon: "Impaler", imbuingSlots: 2 },
  {
    name: "Inferniarch Battleaxe",
    icon: "Inferniarch Battleaxe",
    imbuingSlots: 2,
  },
  {
    name: "Inferniarch Greataxe",
    icon: "Inferniarch Greataxe",
    imbuingSlots: 2,
  },
  { name: "Knight Axe", icon: "Knight Axe", imbuingSlots: 2 },
  { name: "Lion Axe", icon: "Lion Axe", imbuingSlots: 2 },
  { name: "Mythril Axe", icon: "Mythril Axe", imbuingSlots: 2 },
  { name: "Naga Axe", icon: "Naga Axe", imbuingSlots: 2 },
  { name: "Noble Axe", icon: "Noble Axe", imbuingSlots: 2 },
  { name: "Phantasmal Axe", icon: "Phantasmal Axe", imbuingSlots: 2 },
  { name: "Ravager's Axe", icon: "Ravager's Axe", imbuingSlots: 3 },
  {
    name: "Rending Inferniarch Battleaxe",
    icon: "Rending Inferniarch Battleaxe",
    imbuingSlots: 1,
  },
  {
    name: "Rending Inferniarch Greataxe",
    icon: "Rending Inferniarch Greataxe",
    imbuingSlots: 1,
  },
  { name: "Rift Lance", icon: "Rift Lance", imbuingSlots: 3 },
  { name: "Royal Axe", icon: "Royal Axe", imbuingSlots: 2 },
  { name: "Ruthless Axe", icon: "Ruthless Axe", imbuingSlots: 2 },
  { name: "Sanguine Battleaxe", icon: "Sanguine Battleaxe", imbuingSlots: 3 },
  { name: "Sanguine Hatchet", icon: "Sanguine Hatchet", imbuingSlots: 2 },
  {
    name: "Siphoning Inferniarch Battleaxe",
    icon: "Siphoning Inferniarch Battleaxe",
    imbuingSlots: 1,
  },
  {
    name: "Siphoning Inferniarch Greataxe",
    icon: "Siphoning Inferniarch Greataxe",
    imbuingSlots: 1,
  },
  { name: "Solar Axe", icon: "Solar Axe", imbuingSlots: 1 },
  { name: "Soulbiter", icon: "Soulbiter", imbuingSlots: 2 },
  { name: "Souleater (Axe)", icon: "Souleater (Axe)", imbuingSlots: 3 },
  { name: "Stonecutter Axe", icon: "Stonecutter Axe", imbuingSlots: 1 },
  { name: "Throwing Axe", icon: "Throwing Axe", imbuingSlots: 1 },
  { name: "Twin Axe", icon: "Twin Axe", imbuingSlots: 3 },
  { name: "Umbral Axe", icon: "Umbral Axe", imbuingSlots: 1 },
  { name: "Umbral Chopper", icon: "Umbral Chopper", imbuingSlots: 1 },
  { name: "Umbral Master Axe", icon: "Umbral Master Axe", imbuingSlots: 1 },
  {
    name: "Umbral Master Chopper",
    icon: "Umbral Master Chopper",
    imbuingSlots: 2,
  },
  { name: "War Axe", icon: "War Axe", imbuingSlots: 3 },
  { name: "Warrior's Axe", icon: "Warrior's Axe", imbuingSlots: 2 },
  { name: "Zaoan Halberd", icon: "Zaoan Halberd", imbuingSlots: 3 },
];
