export const backpacks = [
  { name: "25 Years Backpack", icon: "25 Years Backpack", imbuingSlots: 1 },
  {
    name: "Anniversary Backpack",
    icon: "Anniversary Backpack",
    imbuingSlots: 1,
  },
  { name: "Backpack of Holding", icon: "Backpack of Holding", imbuingSlots: 1 },
  { name: "Backpack", icon: "Backpack", imbuingSlots: 1 },
  { name: "Beach Backpack", icon: "Beach Backpack", imbuingSlots: 1 },
  { name: "Birthday Backpack", icon: "Birthday Backpack", imbuingSlots: 1 },
  { name: "Blue Backpack", icon: "Blue Backpack", imbuingSlots: 1 },
  { name: "Book Backpack", icon: "Book Backpack", imbuingSlots: 1 },
  { name: "Brocade Backpack", icon: "Brocade Backpack", imbuingSlots: 1 },
  { name: "Buggy Backpack", icon: "Buggy Backpack", imbuingSlots: 1 },
  { name: "Bursa Obscura", icon: "Bursa Obscura", imbuingSlots: 1 },
  { name: "Cake Backpack", icon: "Cake Backpack", imbuingSlots: 1 },
  { name: "Camouflage Backpack", icon: "Camouflage Backpack", imbuingSlots: 1 },
  { name: "Changing Backpack", icon: "Changing Backpack", imbuingSlots: 1 },
  { name: "Crown Backpack", icon: "Crown Backpack", imbuingSlots: 1 },
  { name: "Crystal Backpack", icon: "Crystal Backpack", imbuingSlots: 1 },
  { name: "Deepling Backpack", icon: "Deepling Backpack", imbuingSlots: 1 },
  { name: "Demon Backpack", icon: "Demon Backpack", imbuingSlots: 1 },
  { name: "Dragon Backpack", icon: "Dragon Backpack", imbuingSlots: 1 },
  { name: "Energetic Backpack", icon: "Energetic Backpack", imbuingSlots: 1 },
  { name: "Expedition Backpack", icon: "Expedition Backpack", imbuingSlots: 1 },
  { name: "Feedbag", icon: "Feedbag", imbuingSlots: 1 },
  { name: "Festive Backpack", icon: "Festive Backpack", imbuingSlots: 1 },
  { name: "Fur Backpack", icon: "Fur Backpack", imbuingSlots: 1 },
  { name: "Ghost Backpack", icon: "Ghost Backpack", imbuingSlots: 1 },
  { name: "Glooth Backpack", icon: "Glooth Backpack", imbuingSlots: 1 },
  { name: "Golden Backpack", icon: "Golden Backpack", imbuingSlots: 1 },
  { name: "Green Backpack", icon: "Green Backpack", imbuingSlots: 1 },
  { name: "Grey Backpack", icon: "Grey Backpack", imbuingSlots: 1 },
  { name: "Heart Backpack", icon: "Heart Backpack", imbuingSlots: 1 },
  { name: "Jewelled Backpack", icon: "Jewelled Backpack", imbuingSlots: 1 },
  { name: "Lilypad Backpack", icon: "Lilypad Backpack", imbuingSlots: 1 },
  { name: "Minotaur Backpack", icon: "Minotaur Backpack", imbuingSlots: 1 },
  { name: "Moon Backpack", icon: "Moon Backpack", imbuingSlots: 1 },
  { name: "Mushroom Backpack", icon: "Mushroom Backpack", imbuingSlots: 1 },
  {
    name: "Old and Used Backpack",
    icon: "Old and Used Backpack",
    imbuingSlots: 1,
  },
  { name: "Orange Backpack", icon: "Orange Backpack", imbuingSlots: 1 },
  { name: "Pannier Backpack", icon: "Pannier Backpack", imbuingSlots: 1 },
  { name: "Peppermint Backpack", icon: "Peppermint Backpack", imbuingSlots: 1 },
  { name: "Pillow Backpack", icon: "Pillow Backpack", imbuingSlots: 1 },
  { name: "Pirate Backpack", icon: "Pirate Backpack", imbuingSlots: 1 },
  { name: "Purple Backpack", icon: "Purple Backpack", imbuingSlots: 1 },
  { name: "Raccoon Backpack", icon: "Raccoon Backpack", imbuingSlots: 1 },
  { name: "Red Backpack", icon: "Red Backpack", imbuingSlots: 1 },
  { name: "Santa Backpack", icon: "Santa Backpack", imbuingSlots: 1 },
  { name: "Winged Backpack", icon: "Winged Backpack", imbuingSlots: 1 },
  { name: "Wolf Backpack", icon: "Wolf Backpack", imbuingSlots: 1 },
  { name: "Yellow Backpack", icon: "Yellow Backpack", imbuingSlots: 1 },
];
