export const boots = [
  { name: "Alchemist's Boots", icon: "Alchemist's Boots", imbuingSlots: 1 },
  { name: "Badger Boots", icon: "Badger Boots", imbuingSlots: 1 },
  { name: "Boots of Haste", icon: "Boots of Haste", imbuingSlots: 1 },
  { name: "Bunnyslippers", icon: "Bunnyslippers", imbuingSlots: 1 },
  { name: "Cobra Boots", icon: "Cobra Boots", imbuingSlots: 1 },
  { name: "Coconut Shoes", icon: "Coconut Shoes", imbuingSlots: 1 },
  { name: "Crocodile Boots", icon: "Crocodile Boots", imbuingSlots: 1 },
  { name: "Crystal Boots", icon: "Crystal Boots", imbuingSlots: 1 },
  { name: "Depth Calcei", icon: "Depth Calcei", imbuingSlots: 1 },
  { name: "Dragon Scale Boots", icon: "Dragon Scale Boots", imbuingSlots: 1 },
  { name: "Draken Boots", icon: "Draken Boots", imbuingSlots: 1 },
  { name: "Eldritch Monk Boots", icon: "Eldritch Monk Boots", imbuingSlots: 1 },
  { name: "Feverbloom Boots", icon: "Feverbloom Boots", imbuingSlots: 1 },
  { name: "Frostflower Boots", icon: "Frostflower Boots", imbuingSlots: 1 },
  { name: "Fur Boots", icon: "Fur Boots", imbuingSlots: 1 },
  { name: "Glacier Shoes", icon: "Glacier Shoes", imbuingSlots: 1 },
  { name: "Gnomish Footwraps", icon: "Gnomish Footwraps", imbuingSlots: 1 },
  { name: "Golden Boots", icon: "Golden Boots", imbuingSlots: 1 },
  {
    name: "Green Demon Slippers",
    icon: "Green Demon Slippers",
    imbuingSlots: 1,
  },
  { name: "Guardian Boots", icon: "Guardian Boots", imbuingSlots: 1 },
  { name: "Iks Footwraps", icon: "Iks Footwraps", imbuingSlots: 1 },
  { name: "Leather Boots", icon: "Leather Boots", imbuingSlots: 1 },
  { name: "Lightning Boots", icon: "Lightning Boots", imbuingSlots: 1 },
  { name: "Magma Boots", icon: "Magma Boots", imbuingSlots: 1 },
  { name: "Make-Do Boots", icon: "Make-Do Boots", imbuingSlots: 1 },
  { name: "Makeshift Boots", icon: "Makeshift Boots", imbuingSlots: 1 },
  { name: "Metal Spats", icon: "Metal Spats", imbuingSlots: 1 },
  { name: "Mutant Bone Boots", icon: "Mutant Bone Boots", imbuingSlots: 1 },
  { name: "Oriental Shoes", icon: "Oriental Shoes", imbuingSlots: 1 },
  {
    name: "Pair of Dreamwalkers",
    icon: "Pair of Dreamwalkers",
    imbuingSlots: 1,
  },
  {
    name: "Pair of Nightmare Boots",
    icon: "Pair of Nightmare Boots",
    imbuingSlots: 1,
  },
  {
    name: "Pair of Soulstalkers",
    icon: "Pair of Soulstalkers",
    imbuingSlots: 1,
  },
  { name: "Pair of Soulwalkers", icon: "Pair of Soulwalkers", imbuingSlots: 1 },
  { name: "Patched Boots", icon: "Patched Boots", imbuingSlots: 1 },
  { name: "Pirate Boots", icon: "Pirate Boots", imbuingSlots: 1 },
  { name: "Prismatic Boots", icon: "Prismatic Boots", imbuingSlots: 1 },
  { name: "Sandals", icon: "Sandals", imbuingSlots: 1 },
  { name: "Sanguine Boots", icon: "Sanguine Boots", imbuingSlots: 1 },
  { name: "Sanguine Galoshes", icon: "Sanguine Galoshes", imbuingSlots: 1 },
  { name: "Soulsoles", icon: "Soulsoles", imbuingSlots: 1 },
  { name: "Steel Boots", icon: "Steel Boots", imbuingSlots: 1 },
  { name: "Stoic Iks Boots", icon: "Stoic Iks Boots", imbuingSlots: 1 },
  { name: "Stoic Iks Sandals", icon: "Stoic Iks Sandals", imbuingSlots: 1 },
  { name: "Terra Boots", icon: "Terra Boots", imbuingSlots: 1 },
  { name: "Treader of Torment", icon: "Treader of Torment", imbuingSlots: 1 },
  {
    name: "Vampire Silk Slippers",
    icon: "Vampire Silk Slippers",
    imbuingSlots: 1,
  },
  { name: "Winged Boots", icon: "Winged Boots", imbuingSlots: 1 },
  { name: "Yalahari Footwraps", icon: "Yalahari Footwraps", imbuingSlots: 1 },
  { name: "Zaoan Shoes", icon: "Zaoan Shoes", imbuingSlots: 1 },
];
