export const bows = [
  { name: "Amber Bow", icon: "Amber Bow", imbuingSlots: 3 },
  { name: "Bow of Carving", icon: "Bow of Carving", imbuingSlots: 3 },
  { name: "Bow of Cataclysm", icon: "Bow of Cataclysm", imbuingSlots: 3 },
  { name: "Bow of Destruction", icon: "Bow of Destruction", imbuingSlots: 3 },
  { name: "Bow of Mayhem", icon: "Bow of Mayhem", imbuingSlots: 3 },
  { name: "Bow of Remedy", icon: "Bow of Remedy", imbuingSlots: 3 },
  { name: "Composite Hornbow", icon: "Composite Hornbow", imbuingSlots: 3 },
  {
    name: "Draining Inferniarch Bow",
    icon: "Draining Inferniarch Bow",
    imbuingSlots: 2,
  },
  { name: "Eldritch Bow", icon: "Eldritch Bow", imbuingSlots: 3 },
  { name: "Elvish Bow", icon: "Elvish Bow", imbuingSlots: 3 },
  { name: "Falcon Bow", icon: "Falcon Bow", imbuingSlots: 3 },
  { name: "Gilded Eldritch Bow", icon: "Gilded Eldritch Bow", imbuingSlots: 3 },
  { name: "Grand Sanguine Bow", icon: "Grand Sanguine Bow", imbuingSlots: 3 },
  { name: "Hive Bow", icon: "Hive Bow", imbuingSlots: 3 },
  { name: "Icicle Bow", icon: "Icicle Bow", imbuingSlots: 3 },
  { name: "Inferniarch Bow", icon: "Inferniarch Bow", imbuingSlots: 3 },
  { name: "Jungle Bow", icon: "Jungle Bow", imbuingSlots: 2 },
  { name: "Lion Longbow", icon: "Lion Longbow", imbuingSlots: 3 },
  { name: "Living Vine Bow", icon: "Living Vine Bow", imbuingSlots: 3 },
  { name: "Musician's Bow", icon: "Musician's Bow", imbuingSlots: 3 },
  { name: "Mycological Bow", icon: "Mycological Bow", imbuingSlots: 3 },
  {
    name: "Rending Inferniarch Bow",
    icon: "Rending Inferniarch Bow",
    imbuingSlots: 2,
  },
  { name: "Rift Bow", icon: "Rift Bow", imbuingSlots: 3 },
  { name: "Sanguine Bow", icon: "Sanguine Bow", imbuingSlots: 3 },
  { name: "Silkweaver Bow", icon: "Silkweaver Bow", imbuingSlots: 3 },
  {
    name: "Siphoning Inferniarch Bow",
    icon: "Siphoning Inferniarch Bow",
    imbuingSlots: 2,
  },
  { name: "Soulbleeder", icon: "Soulbleeder", imbuingSlots: 3 },
  { name: "Umbral Bow", icon: "Umbral Bow", imbuingSlots: 1 },
  { name: "Umbral Master Bow", icon: "Umbral Master Bow", imbuingSlots: 2 },
  { name: "Warsinger Bow", icon: "Warsinger Bow", imbuingSlots: 3 },
];
