export const clubs = [
  { name: "Abyss Hammer", icon: "Abyss Hammer", imbuingSlots: 3 },
  { name: "Amber Bludgeon", icon: "Amber Bludgeon", imbuingSlots: 2 },
  { name: "Amber Cudgel", icon: "Amber Cudgel", imbuingSlots: 2 },
  { name: "Amber Staff", icon: "Amber Staff", imbuingSlots: 3 },
  { name: "Arcane Staff", icon: "Arcane Staff", imbuingSlots: 2 },
  { name: "Blessed Sceptre", icon: "Blessed Sceptre", imbuingSlots: 2 },
  { name: "Clerical Mace", icon: "Clerical Mace", imbuingSlots: 2 },
  { name: "Cobra Club", icon: "Cobra Club", imbuingSlots: 2 },
  { name: "Cranial Basher", icon: "Cranial Basher", imbuingSlots: 2 },
  { name: "Crystal Mace", icon: "Crystal Mace", imbuingSlots: 2 },
  { name: "Deepling Squelcher", icon: "Deepling Squelcher", imbuingSlots: 2 },
  { name: "Demonbone", icon: "Demonbone", imbuingSlots: 2 },
  { name: "Dragonbone Staff", icon: "Dragonbone Staff", imbuingSlots: 2 },
  {
    name: "Draining Inferniarch Flail",
    icon: "Draining Inferniarch Flail",
    imbuingSlots: 1,
  },
  {
    name: "Draining Inferniarch Warhammer",
    icon: "Draining Inferniarch Warhammer",
    imbuingSlots: 1,
  },
  { name: "Eldritch Warmace", icon: "Eldritch Warmace", imbuingSlots: 2 },
  { name: "Energized Demonbone", icon: "Energized Demonbone", imbuingSlots: 2 },
  { name: "Falcon Mace", icon: "Falcon Mace", imbuingSlots: 2 },
  {
    name: "Gilded Eldritch Warmace",
    icon: "Gilded Eldritch Warmace",
    imbuingSlots: 2,
  },
  { name: "Glooth Whip", icon: "Glooth Whip", imbuingSlots: 2 },
  {
    name: "Grand Sanguine Bludgeon",
    icon: "Grand Sanguine Bludgeon",
    imbuingSlots: 3,
  },
  {
    name: "Grand Sanguine Cudgel",
    icon: "Grand Sanguine Cudgel",
    imbuingSlots: 2,
  },
  { name: "Hammer of Carving", icon: "Hammer of Carving", imbuingSlots: 3 },
  {
    name: "Hammer of Destruction",
    icon: "Hammer of Destruction",
    imbuingSlots: 3,
  },
  { name: "Hammer of Mayhem", icon: "Hammer of Mayhem", imbuingSlots: 3 },
  { name: "Hammer of Remedy", icon: "Hammer of Remedy", imbuingSlots: 3 },
  { name: "Hammer of Wrath", icon: "Hammer of Wrath", imbuingSlots: 3 },
  { name: "Heavy Mace", icon: "Heavy Mace", imbuingSlots: 3 },
  { name: "Inferniarch Flail", icon: "Inferniarch Flail", imbuingSlots: 2 },
  {
    name: "Inferniarch Warhammer",
    icon: "Inferniarch Warhammer",
    imbuingSlots: 2,
  },
  { name: "Jungle Flail", icon: "Jungle Flail", imbuingSlots: 2 },
  { name: "Life Preserver", icon: "Life Preserver", imbuingSlots: 2 },
  { name: "Lion Hammer", icon: "Lion Hammer", imbuingSlots: 2 },
  { name: "Lunar Staff", icon: "Lunar Staff", imbuingSlots: 3 },
  { name: "Mace of Carving", icon: "Mace of Carving", imbuingSlots: 3 },
  { name: "Mace of Destruction", icon: "Mace of Destruction", imbuingSlots: 2 },
  { name: "Mace of Mayhem", icon: "Mace of Mayhem", imbuingSlots: 3 },
  { name: "Mace of Remedy", icon: "Mace of Remedy", imbuingSlots: 3 },
  { name: "Maimer", icon: "Maimer", imbuingSlots: 1 },
  { name: "Mortal Mace", icon: "Mortal Mace", imbuingSlots: 2 },
  { name: "Mycological Mace", icon: "Mycological Mace", imbuingSlots: 1 },
  { name: "Naga Club", icon: "Naga Club", imbuingSlots: 2 },
  { name: "Obsidian Truncheon", icon: "Obsidian Truncheon", imbuingSlots: 1 },
  { name: "Onyx Flail", icon: "Onyx Flail", imbuingSlots: 2 },
  { name: "Orcish Maul", icon: "Orcish Maul", imbuingSlots: 3 },
  { name: "Ornate Mace", icon: "Ornate Mace", imbuingSlots: 2 },
  { name: "Queen's Sceptre", icon: "Queen's Sceptre", imbuingSlots: 2 },
  {
    name: "Rending Inferniarch Flail",
    icon: "Rending Inferniarch Flail",
    imbuingSlots: 1,
  },
  {
    name: "Rending Inferniarch Warhammer",
    icon: "Rending Inferniarch Warhammer",
    imbuingSlots: 1,
  },
  { name: "Resizer", icon: "Resizer", imbuingSlots: 2 },
  { name: "Rotten Demonbone", icon: "Rotten Demonbone", imbuingSlots: 2 },
  { name: "Sanguine Bludgeon", icon: "Sanguine Bludgeon", imbuingSlots: 3 },
  { name: "Sanguine Cudgel", icon: "Sanguine Cudgel", imbuingSlots: 2 },
  { name: "Sapphire Hammer", icon: "Sapphire Hammer", imbuingSlots: 2 },
  { name: "Shadow Sceptre", icon: "Shadow Sceptre", imbuingSlots: 2 },
  { name: "Silver Mace", icon: "Silver Mace", imbuingSlots: 2 },
  {
    name: "Siphoning Inferniarch Flail",
    icon: "Siphoning Inferniarch Flail",
    imbuingSlots: 1,
  },
  {
    name: "Siphoning Inferniarch Warhammer",
    icon: "Siphoning Inferniarch Warhammer",
    imbuingSlots: 1,
  },
  { name: "Skull Staff", icon: "Skull Staff", imbuingSlots: 2 },
  { name: "Skullcrusher", icon: "Skullcrusher", imbuingSlots: 2 },
  { name: "Snake God's Sceptre", icon: "Snake God's Sceptre", imbuingSlots: 2 },
  { name: "Soulcrusher", icon: "Soulcrusher", imbuingSlots: 2 },
  { name: "Soulmaimer", icon: "Soulmaimer", imbuingSlots: 3 },
  { name: "Spiked Squelcher", icon: "Spiked Squelcher", imbuingSlots: 3 },
  {
    name: "Sulphurous Demonbone",
    icon: "Sulphurous Demonbone",
    imbuingSlots: 2,
  },
  { name: "The Stomper", icon: "The Stomper", imbuingSlots: 2 },
  { name: "Thunder Hammer", icon: "Thunder Hammer", imbuingSlots: 2 },
  { name: "Umbral Hammer", icon: "Umbral Hammer", imbuingSlots: 1 },
  { name: "Umbral Mace", icon: "Umbral Mace", imbuingSlots: 1 },
  {
    name: "Umbral Master Hammer",
    icon: "Umbral Master Hammer",
    imbuingSlots: 2,
  },
  { name: "Umbral Master Mace", icon: "Umbral Master Mace", imbuingSlots: 1 },
  { name: "Unliving Demonbone", icon: "Unliving Demonbone", imbuingSlots: 2 },
  { name: "War Hammer", icon: "War Hammer", imbuingSlots: 3 },
];
