export const crossbows = [
  { name: "Amber Crossbow", icon: "Amber Crossbow", imbuingSlots: 3 },
  { name: "Chain Bolter", icon: "Chain Bolter", imbuingSlots: 3 },
  { name: "Cobra Crossbow", icon: "Cobra Crossbow", imbuingSlots: 2 },
  { name: "Crossbow of Carving", icon: "Crossbow of Carving", imbuingSlots: 3 },
  {
    name: "Crossbow of Destruction",
    icon: "Crossbow of Destruction",
    imbuingSlots: 3,
  },
  { name: "Crossbow of Mayhem", icon: "Crossbow of Mayhem", imbuingSlots: 3 },
  { name: "Crossbow of Remedy", icon: "Crossbow of Remedy", imbuingSlots: 3 },
  { name: "Crossbow", icon: "Crossbow", imbuingSlots: 3 },
  {
    name: "Draining Inferniarch Arbalest",
    icon: "Draining Inferniarch Arbalest",
    imbuingSlots: 2,
  },
  {
    name: "Grand Sanguine Crossbow",
    icon: "Grand Sanguine Crossbow",
    imbuingSlots: 3,
  },
  {
    name: "Inferniarch Arbalest",
    icon: "Inferniarch Arbalest",
    imbuingSlots: 3,
  },
  { name: "Modified Crossbow", icon: "Modified Crossbow", imbuingSlots: 3 },
  { name: "Naga Crossbow", icon: "Naga Crossbow", imbuingSlots: 3 },
  {
    name: "Rending Inferniarch Arbalest",
    icon: "Rending Inferniarch Arbalest",
    imbuingSlots: 2,
  },
  { name: "Rift Crossbow", icon: "Rift Crossbow", imbuingSlots: 3 },
  { name: "Royal Crossbow", icon: "Royal Crossbow", imbuingSlots: 3 },
  { name: "Sanguine Crossbow", icon: "Sanguine Crossbow", imbuingSlots: 3 },
  {
    name: "Siphoning Inferniarch Arbalest",
    icon: "Siphoning Inferniarch Arbalest",
    imbuingSlots: 2,
  },
  { name: "Soulpiercer", icon: "Soulpiercer", imbuingSlots: 3 },
  { name: "The Devileye", icon: "The Devileye", imbuingSlots: 3 },
  { name: "The Ironworker", icon: "The Ironworker", imbuingSlots: 3 },
  { name: "Thorn Spitter", icon: "Thorn Spitter", imbuingSlots: 3 },
  {
    name: "Triple Bolt Crossbow",
    icon: "Triple Bolt Crossbow",
    imbuingSlots: 3,
  },
  { name: "Umbral Crossbow", icon: "Umbral Crossbow", imbuingSlots: 1 },
  {
    name: "Umbral Master Crossbow",
    icon: "Umbral Master Crossbow",
    imbuingSlots: 2,
  },
];
