export const helmets = [
  { name: "Alicorn Headguard", icon: "Alicorn Headguard", imbuingSlots: 2 },
  { name: "Amazon Helmet", icon: "Amazon Helmet", imbuingSlots: 2 },
  { name: "Ancient Tiara", icon: "Ancient Tiara", imbuingSlots: 2 },
  { name: "Antler-Horn Helmet", icon: "Antler-Horn Helmet", imbuingSlots: 2 },
  { name: "Arboreal Crown", icon: "Arboreal Crown", imbuingSlots: 2 },
  {
    name: "Arcanomancer Regalia",
    icon: "Arcanomancer Regalia",
    imbuingSlots: 2,
  },
  { name: "Batwing Hat", icon: "Batwing Hat", imbuingSlots: 1 },
  { name: "Bonelord Helmet", icon: "Bonelord Helmet", imbuingSlots: 2 },
  { name: "Cobra Hood", icon: "Cobra Hood", imbuingSlots: 2 },
  {
    name: "Coned Hat of Enlightenment",
    icon: "Coned Hat of Enlightenment",
    imbuingSlots: 1,
  },
  {
    name: "Coned Hat of Spirits",
    icon: "Coned Hat of Spirits",
    imbuingSlots: 2,
  },
  { name: "Crown Helmet", icon: "Crown Helmet", imbuingSlots: 2 },
  { name: "Crusader Helmet", icon: "Crusader Helmet", imbuingSlots: 2 },
  { name: "Dark Vision Bandana", icon: "Dark Vision Bandana", imbuingSlots: 2 },
  { name: "Dark Whispers", icon: "Dark Whispers", imbuingSlots: 2 },
  { name: "Demon Helmet", icon: "Demon Helmet", imbuingSlots: 2 },
  { name: "Demon Mengu", icon: "Demon Mengu", imbuingSlots: 2 },
  { name: "Demonfang Mask", icon: "Demonfang Mask", imbuingSlots: 2 },
  { name: "Dreadfire Headpiece", icon: "Dreadfire Headpiece", imbuingSlots: 2 },
  { name: "Dwarven Helmet", icon: "Dwarven Helmet", imbuingSlots: 2 },
  { name: "Eldritch Cowl", icon: "Eldritch Cowl", imbuingSlots: 2 },
  { name: "Eldritch Hood", icon: "Eldritch Hood", imbuingSlots: 2 },
  { name: "Elite Draken Helmet", icon: "Elite Draken Helmet", imbuingSlots: 1 },
  { name: "Falcon Circlet", icon: "Falcon Circlet", imbuingSlots: 2 },
  { name: "Falcon Coif", icon: "Falcon Coif", imbuingSlots: 2 },
  { name: "Fur Cap", icon: "Fur Cap", imbuingSlots: 2 },
  { name: "Galea Mortis", icon: "Galea Mortis", imbuingSlots: 2 },
  { name: "Gnome Helmet", icon: "Gnome Helmet", imbuingSlots: 2 },
  { name: "Golden Helmet", icon: "Golden Helmet", imbuingSlots: 2 },
  { name: "Green Demon Helmet", icon: "Green Demon Helmet", imbuingSlots: 2 },
  { name: "Hat of the Mad", icon: "Hat of the Mad", imbuingSlots: 1 },
  { name: "Hellstalker Visor", icon: "Hellstalker Visor", imbuingSlots: 2 },
  { name: "Helmet of Nature", icon: "Helmet of Nature", imbuingSlots: 2 },
  {
    name: "Helmet of Ultimate Terror",
    icon: "Helmet of Ultimate Terror",
    imbuingSlots: 2,
  },
  { name: "Helmet of the Lost", icon: "Helmet of the Lost", imbuingSlots: 2 },
  { name: "Jade Conical Hat", icon: "Jade Conical Hat", imbuingSlots: 1 },
  { name: "Jade Hat", icon: "Jade Hat", imbuingSlots: 1 },
  { name: "Lion Spangenhelm", icon: "Lion Spangenhelm", imbuingSlots: 2 },
  { name: "Mage Hat", icon: "Mage Hat", imbuingSlots: 2 },
  { name: "Magician Hat", icon: "Magician Hat", imbuingSlots: 2 },
  { name: "Maliceforged Helmet", icon: "Maliceforged Helmet", imbuingSlots: 2 },
  { name: "Odd Hat", icon: "Odd Hat", imbuingSlots: 2 },
  { name: "Royal Helmet", icon: "Royal Helmet", imbuingSlots: 2 },
  { name: "Shamanic Mask", icon: "Shamanic Mask", imbuingSlots: 2 },
  { name: "Skull Helmet", icon: "Skull Helmet", imbuingSlots: 2 },
  { name: "Spiritthorn Helmet", icon: "Spiritthorn Helmet", imbuingSlots: 2 },
  { name: "Stoic Iks Casque", icon: "Stoic Iks Casque", imbuingSlots: 2 },
  { name: "Stoic Iks Headpiece", icon: "Stoic Iks Headpiece", imbuingSlots: 2 },
  { name: "Terra Helmet", icon: "Terra Helmet", imbuingSlots: 1 },
  {
    name: "Visage of the End Days",
    icon: "Visage of the End Days",
    imbuingSlots: 2,
  },
  { name: "Warrior Helmet", icon: "Warrior Helmet", imbuingSlots: 2 },
  { name: "Witch Hat", icon: "Witch Hat", imbuingSlots: 1 },
  { name: "Yalahari Mask", icon: "Yalahari Mask", imbuingSlots: 1 },
  { name: "Zaoan Helmet", icon: "Zaoan Helmet", imbuingSlots: 1 },
];
