export const rods = [
  { name: "Amber Rod", icon: "Amber Rod", imbuingSlots: 2 },
  { name: "Cobra Rod", icon: "Cobra Rod", imbuingSlots: 2 },
  {
    name: "Deepling Ceremonial Dagger",
    icon: "Deepling Ceremonial Dagger",
    imbuingSlots: 2,
  },
  { name: "Deepling Fork", icon: "Deepling Fork", imbuingSlots: 2 },
  {
    name: "Draining Inferniarch Rod",
    icon: "Draining Inferniarch Rod",
    imbuingSlots: 1,
  },
  { name: "Dream Blossom Staff", icon: "Dream Blossom Staff", imbuingSlots: 2 },
  { name: "Eldritch Rod", icon: "Eldritch Rod", imbuingSlots: 2 },
  { name: "Energized Limb", icon: "Energized Limb", imbuingSlots: 2 },
  { name: "Falcon Rod", icon: "Falcon Rod", imbuingSlots: 2 },
  { name: "Gilded Eldritch Rod", icon: "Gilded Eldritch Rod", imbuingSlots: 2 },
  { name: "Grand Sanguine Rod", icon: "Grand Sanguine Rod", imbuingSlots: 2 },
  { name: "Inferniarch Rod", icon: "Inferniarch Rod", imbuingSlots: 2 },
  { name: "Jungle Rod", icon: "Jungle Rod", imbuingSlots: 2 },
  { name: "Lion Rod", icon: "Lion Rod", imbuingSlots: 2 },
  { name: "Naga Rod", icon: "Naga Rod", imbuingSlots: 2 },
  { name: "Northwind Rod", icon: "Northwind Rod", imbuingSlots: 2 },
  { name: "Ogre Scepta", icon: "Ogre Scepta", imbuingSlots: 2 },
  {
    name: "Rending Inferniarch Rod",
    icon: "Rending Inferniarch Rod",
    imbuingSlots: 1,
  },
  { name: "Rod of Carving", icon: "Rod of Carving", imbuingSlots: 2 },
  { name: "Rod of Destruction", icon: "Rod of Destruction", imbuingSlots: 2 },
  { name: "Rod of Mayhem", icon: "Rod of Mayhem", imbuingSlots: 2 },
  { name: "Rod of Remedy", icon: "Rod of Remedy", imbuingSlots: 2 },
  { name: "Sanguine Rod", icon: "Sanguine Rod", imbuingSlots: 2 },
  {
    name: "Siphoning Inferniarch Rod",
    icon: "Siphoning Inferniarch Rod",
    imbuingSlots: 1,
  },
  { name: "Soulhexer", icon: "Soulhexer", imbuingSlots: 2 },
  { name: "Underworld Rod", icon: "Underworld Rod", imbuingSlots: 2 },
];
