export const shields = [
  { name: "Amazon Shield", icon: "Amazon Shield", imbuingSlots: 1 },
  { name: "Biscuit Barrier", icon: "Biscuit Barrier", imbuingSlots: 1 },
  { name: "Bonelord Shield", icon: "Bonelord Shield", imbuingSlots: 1 },
  { name: "Carapace Shield", icon: "Carapace Shield", imbuingSlots: 1 },
  { name: "Castle Shield", icon: "Castle Shield", imbuingSlots: 1 },
  { name: "Crown Shield", icon: "Crown Shield", imbuingSlots: 1 },
  { name: "Death Gaze", icon: "Death Gaze", imbuingSlots: 1 },
  { name: "Demon Shield", icon: "Demon Shield", imbuingSlots: 1 },
  { name: "Depth Scutum", icon: "Depth Scutum", imbuingSlots: 1 },
  { name: "Dragon Shield", icon: "Dragon Shield", imbuingSlots: 1 },
  { name: "Ectoplasmic Shield", icon: "Ectoplasmic Shield", imbuingSlots: 1 },
  { name: "Eldritch Shield", icon: "Eldritch Shield", imbuingSlots: 1 },
  { name: "Falcon Escutcheon", icon: "Falcon Escutcheon", imbuingSlots: 1 },
  { name: "Falcon Shield", icon: "Falcon Shield", imbuingSlots: 1 },
  { name: "Gnome Shield", icon: "Gnome Shield", imbuingSlots: 1 },
  { name: "Great Shield", icon: "Great Shield", imbuingSlots: 1 },
  { name: "Griffin Shield", icon: "Griffin Shield", imbuingSlots: 1 },
  {
    name: "Haunted Mirror Piece",
    icon: "Haunted Mirror Piece",
    imbuingSlots: 1,
  },
  { name: "Lion Shield", icon: "Lion Shield", imbuingSlots: 1 },
  { name: "Mastermind Shield", icon: "Mastermind Shield", imbuingSlots: 1 },
  { name: "Meat Shield", icon: "Meat Shield", imbuingSlots: 1 },
  { name: "Medusa Shield", icon: "Medusa Shield", imbuingSlots: 1 },
  { name: "Necromancer Shield", icon: "Necromancer Shield", imbuingSlots: 1 },
  { name: "Nightmare Shield", icon: "Nightmare Shield", imbuingSlots: 1 },
  { name: "Norse Shield", icon: "Norse Shield", imbuingSlots: 1 },
  { name: "Ornamented Shield", icon: "Ornamented Shield", imbuingSlots: 1 },
  { name: "Ornate Shield", icon: "Ornate Shield", imbuingSlots: 1 },
  { name: "Phoenix Shield", icon: "Phoenix Shield", imbuingSlots: 1 },
  { name: "Rift Shield", icon: "Rift Shield", imbuingSlots: 1 },
  { name: "Runic Ice Shield", icon: "Runic Ice Shield", imbuingSlots: 1 },
  { name: "Sentinel Shield", icon: "Sentinel Shield", imbuingSlots: 1 },
  { name: "Shield of Care", icon: "Shield of Care", imbuingSlots: 1 },
  {
    name: "Shield of Corruption",
    icon: "Shield of Corruption",
    imbuingSlots: 1,
  },
  {
    name: "Shield of the White Knight",
    icon: "Shield of the White Knight",
    imbuingSlots: 1,
  },
  { name: "Soulbastion", icon: "Soulbastion", imbuingSlots: 1 },
  { name: "Steel Shield", icon: "Steel Shield", imbuingSlots: 1 },
  { name: "Tempest Shield", icon: "Tempest Shield", imbuingSlots: 1 },
  { name: "Tower Shield", icon: "Tower Shield", imbuingSlots: 1 },
  { name: "Vampire Shield", icon: "Vampire Shield", imbuingSlots: 1 },
  { name: "Viking Shield", icon: "Viking Shield", imbuingSlots: 1 },
  { name: "Warrior's Shield", icon: "Warrior's Shield", imbuingSlots: 1 },
];
