export const swords = [
  { name: "Amber Sabre", icon: "Amber Sabre", imbuingSlots: 2 },
  { name: "Amber Slayer", icon: "Amber Slayer", imbuingSlots: 2 },
  { name: "Assassin Dagger", icon: "Assassin Dagger", imbuingSlots: 2 },
  { name: "Berserker", icon: "Berserker", imbuingSlots: 3 },
  { name: "Blacksteel Sword", icon: "Blacksteel Sword", imbuingSlots: 3 },
  { name: "Blade of Carving", icon: "Blade of Carving", imbuingSlots: 3 },
  { name: "Blade of Corruption", icon: "Blade of Corruption", imbuingSlots: 2 },
  {
    name: "Blade of Destruction",
    icon: "Blade of Destruction",
    imbuingSlots: 2,
  },
  { name: "Blade of Mayhem", icon: "Blade of Mayhem", imbuingSlots: 3 },
  { name: "Blade of Remedy", icon: "Blade of Remedy", imbuingSlots: 3 },
  { name: "Bloody Edge", icon: "Bloody Edge", imbuingSlots: 2 },
  { name: "Bright Sword", icon: "Bright Sword", imbuingSlots: 2 },
  { name: "Broadsword", icon: "Broadsword", imbuingSlots: 3 },
  { name: "Cobra Sword", icon: "Cobra Sword", imbuingSlots: 2 },
  { name: "Crimson Sword", icon: "Crimson Sword", imbuingSlots: 2 },
  { name: "Demonrage Sword", icon: "Demonrage Sword", imbuingSlots: 3 },
  { name: "Djinn Blade", icon: "Djinn Blade", imbuingSlots: 2 },
  { name: "Dragon Slayer", icon: "Dragon Slayer", imbuingSlots: 3 },
  {
    name: "Draining Inferniarch Blade",
    icon: "Draining Inferniarch Blade",
    imbuingSlots: 1,
  },
  {
    name: "Draining Inferniarch Slayer",
    icon: "Draining Inferniarch Slayer",
    imbuingSlots: 1,
  },
  { name: "Eldritch Claymore", icon: "Eldritch Claymore", imbuingSlots: 2 },
  { name: "Emerald Sword", icon: "Emerald Sword", imbuingSlots: 2 },
  { name: "Epee", icon: "Epee", imbuingSlots: 2 },
  { name: "Falcon Longsword", icon: "Falcon Longsword", imbuingSlots: 2 },
  { name: "Giant Sword", icon: "Giant Sword", imbuingSlots: 3 },
  {
    name: "Gilded Eldritch Claymore",
    icon: "Gilded Eldritch Claymore",
    imbuingSlots: 2,
  },
  { name: "Gnome Sword", icon: "Gnome Sword", imbuingSlots: 2 },
  {
    name: "Grand Sanguine Blade",
    icon: "Grand Sanguine Blade",
    imbuingSlots: 2,
  },
  {
    name: "Grand Sanguine Razor",
    icon: "Grand Sanguine Razor",
    imbuingSlots: 3,
  },
  { name: "Haunted Blade", icon: "Haunted Blade", imbuingSlots: 3 },
  { name: "Havoc Blade", icon: "Havoc Blade", imbuingSlots: 3 },
  { name: "Inferniarch Blade", icon: "Inferniarch Blade", imbuingSlots: 2 },
  { name: "Inferniarch Slayer", icon: "Inferniarch Slayer", imbuingSlots: 2 },
  { name: "Lion Longsword", icon: "Lion Longsword", imbuingSlots: 2 },
  { name: "Magic Sword", icon: "Magic Sword", imbuingSlots: 2 },
  { name: "Mystic Blade", icon: "Mystic Blade", imbuingSlots: 2 },
  { name: "Naga Sword", icon: "Naga Sword", imbuingSlots: 2 },
  { name: "Nightmare Blade", icon: "Nightmare Blade", imbuingSlots: 2 },
  { name: "Relic Sword", icon: "Relic Sword", imbuingSlots: 2 },
  {
    name: "Rending Inferniarch Blade",
    icon: "Rending Inferniarch Blade",
    imbuingSlots: 1,
  },
  {
    name: "Rending Inferniarch Slayer",
    icon: "Rending Inferniarch Slayer",
    imbuingSlots: 1,
  },
  { name: "Runed Sword", icon: "Runed Sword", imbuingSlots: 2 },
  { name: "Sanguine Blade", icon: "Sanguine Blade", imbuingSlots: 2 },
  { name: "Sanguine Razor", icon: "Sanguine Razor", imbuingSlots: 3 },
  { name: "Shiny Blade", icon: "Shiny Blade", imbuingSlots: 1 },
  {
    name: "Siphoning Inferniarch Blade",
    icon: "Siphoning Inferniarch Blade",
    imbuingSlots: 1,
  },
  {
    name: "Siphoning Inferniarch Slayer",
    icon: "Siphoning Inferniarch Slayer",
    imbuingSlots: 1,
  },
  { name: "Slayer of Carving", icon: "Slayer of Carving", imbuingSlots: 3 },
  {
    name: "Slayer of Destruction",
    icon: "Slayer of Destruction",
    imbuingSlots: 3,
  },
  { name: "Slayer of Mayhem", icon: "Slayer of Mayhem", imbuingSlots: 3 },
  { name: "Slayer of Remedy", icon: "Slayer of Remedy", imbuingSlots: 3 },
  { name: "Soulcutter", icon: "Soulcutter", imbuingSlots: 2 },
  { name: "Soulshredder", icon: "Soulshredder", imbuingSlots: 3 },
  { name: "Spike Sword", icon: "Spike Sword", imbuingSlots: 2 },
  { name: "Summerblade", icon: "Summerblade", imbuingSlots: 2 },
  { name: "Sword", icon: "Sword", imbuingSlots: 2 },
  { name: "Tagralt Blade", icon: "Tagralt Blade", imbuingSlots: 2 },
  { name: "Thaian Sword", icon: "Thaian Sword", imbuingSlots: 3 },
  { name: "The Avenger", icon: "The Avenger", imbuingSlots: 2 },
  { name: "The Epiphany", icon: "The Epiphany", imbuingSlots: 1 },
  { name: "Twiceslicer", icon: "Twiceslicer", imbuingSlots: 3 },
  { name: "Twin Hooks", icon: "Twin Hooks", imbuingSlots: 3 },
  { name: "Umbral Blade", icon: "Umbral Blade", imbuingSlots: 1 },
  {
    name: "Umbral Master Slayer",
    icon: "Umbral Master Slayer",
    imbuingSlots: 2,
  },
  { name: "Umbral Masterblade", icon: "Umbral Masterblade", imbuingSlots: 1 },
  { name: "Umbral Slayer", icon: "Umbral Slayer", imbuingSlots: 1 },
  { name: "Winterblade", icon: "Winterblade", imbuingSlots: 2 },
  { name: "Wyvern Fang", icon: "Wyvern Fang", imbuingSlots: 2 },
  { name: "Zaoan Sword", icon: "Zaoan Sword", imbuingSlots: 2 },
];
