export const wands = [
  { name: "Amber Wand", icon: "Amber Wand", imbuingSlots: 2 },
  { name: "Cobra Wand", icon: "Cobra Wand", imbuingSlots: 2 },
  {
    name: "Deepling Ceremonial Dagger",
    icon: "Deepling Ceremonial Dagger",
    imbuingSlots: 2,
  },
  { name: "Deepling Fork", icon: "Deepling Fork", imbuingSlots: 2 },
  {
    name: "Draining Inferniarch Wand",
    icon: "Draining Inferniarch Wand",
    imbuingSlots: 1,
  },
  { name: "Dream Blossom Staff", icon: "Dream Blossom Staff", imbuingSlots: 2 },
  { name: "Eldritch Wand", icon: "Eldritch Wand", imbuingSlots: 2 },
  { name: "Energized Limb", icon: "Energized Limb", imbuingSlots: 2 },
  { name: "Falcon Wand", icon: "Falcon Wand", imbuingSlots: 2 },
  {
    name: "Gilded Eldritch Wand",
    icon: "Gilded Eldritch Wand",
    imbuingSlots: 2,
  },
  { name: "Grand Sanguine Coil", icon: "Grand Sanguine Coil", imbuingSlots: 2 },
  { name: "Inferniarch Wand", icon: "Inferniarch Wand", imbuingSlots: 2 },
  { name: "Jungle Wand", icon: "Jungle Wand", imbuingSlots: 2 },
  { name: "Lion Wand", icon: "Lion Wand", imbuingSlots: 2 },
  { name: "Naga Wand", icon: "Naga Wand", imbuingSlots: 2 },
  {
    name: "Rending Inferniarch Wand",
    icon: "Rending Inferniarch Wand",
    imbuingSlots: 1,
  },
  { name: "Sanguine Coil", icon: "Sanguine Coil", imbuingSlots: 2 },
  {
    name: "Siphoning Inferniarch Wand",
    icon: "Siphoning Inferniarch Wand",
    imbuingSlots: 1,
  },
  { name: "Soultainter", icon: "Soultainter", imbuingSlots: 2 },
  { name: "Wand of Carving", icon: "Wand of Carving", imbuingSlots: 2 },
  { name: "Wand of Destruction", icon: "Wand of Destruction", imbuingSlots: 2 },
  { name: "Wand of Draconia", icon: "Wand of Draconia", imbuingSlots: 2 },
  {
    name: "Wand of Dragonbreath",
    icon: "Wand of Dragonbreath",
    imbuingSlots: 2,
  },
  { name: "Wand of Mayhem", icon: "Wand of Mayhem", imbuingSlots: 2 },
  { name: "Wand of Remedy", icon: "Wand of Remedy", imbuingSlots: 2 },
  { name: "Wand of Starstorm", icon: "Wand of Starstorm", imbuingSlots: 2 },
  { name: "Wand of Voodoo", icon: "Wand of Voodoo", imbuingSlots: 2 },
];
