export const imbuementsTypes = {
  basic: {
    price: 5000,
    successRate: 90,
    priceForFullSucess: 10000,
    premium: false,
  },
  intricate: {
    price: 30000,
    successRate: 70,
    priceForFullSuccess: 30000,
    premium: true,
  },
  powerful: {
    price: 200000,
    successRate: 50,
    priceForFullSuccess: 50000,
    premium: true,
  },
};

export const imbuingsAvailableByType = {
  armors: [
    "deathProtection",
    "energyProtection",
    "holyProtection",
    "iceProtection",
    "earthProtection",
    "fireProtection",
    "lifeLeech",
  ],
  boots: ["velocityIncrease", "paralysisRemoval"],
  bows: [
    "distanceSkill",
    "deathDamage",
    "earthDamage",
    "energyDamage",
    "fireDamage",
    "iceDamage",
    "lifeLeech",
    "manaLeech",
    "criticalDamage",
  ],
  crossbows: [
    "distanceSkill",
    "deathDamage",
    "earthDamage",
    "energyDamage",
    "fireDamage",
    "iceDamage",
    "lifeLeech",
    "manaLeech",
    "criticalDamage",
  ],
  helmets: [
    "axeSkill",
    "clubSkill",
    "swordSkill",
    "shieldingSkill",
    "distanceSkill",
    "magicLevel",
    "manaLeech",
  ], // Magic Level has exceptions
  rods: ["magicLevel", "lifeLeech", "manaLeech", "criticalDamage"], // Critical has exceptions
  wands: ["magicLevel", "lifeLeech", "manaLeech", "criticalDamage"], // Critical has exceptions
  shields: [
    "deathProtection",
    "energyProtection",
    "holyProtection",
    "iceProtection",
    "earthProtection",
    "fireProtection",
    "shieldingSkill",
  ],
  spellbooks: [
    "deathProtection",
    "energyProtection",
    "holyProtection",
    "iceProtection",
    "earthProtection",
    "fireProtection",
    "shieldingSkill",
  ],
  axes: [
    "axeSkill",
    "clubSkill",
    "swordSkill",
    "deathDamage",
    "earthDamage",
    "energyDamage",
    "fireDamage",
    "iceDamage",
    "lifeLeech",
    "manaLeech",
    "criticalDamage",
  ],
  clubs: [
    "axeSkill",
    "clubSkill",
    "swordSkill",
    "deathDamage",
    "earthDamage",
    "energyDamage",
    "fireDamage",
    "iceDamage",
    "lifeLeech",
    "manaLeech",
    "criticalDamage",
  ],
  swords: [
    "axeSkill",
    "clubSkill",
    "swordSkill",
    "deathDamage",
    "earthDamage",
    "energyDamage",
    "fireDamage",
    "iceDamage",
    "lifeLeech",
    "manaLeech",
    "criticalDamage",
  ],
  backpacks: ["capacityIncrease"],
};

export const imbuements = {
  deathProtection: {
    name: "Lich Shroud",
    effect: "Death Protection",
    basic: [{ itemName: "Flask of Embalming Fluid", quantity: 25 }],
    intricate: [
      { itemName: "Flask of Embalming Fluid", quantity: 25 },
      { itemName: "Gloom Wolf Fur", quantity: 20 },
    ],
    powerful: [
      { itemName: "Flask of Embalming Fluid", quantity: 25 },
      { itemName: "Gloom Wolf Fur", quantity: 20 },
      { itemName: "Mystical Hourglass", quantity: 5 },
    ],
    icon: "deathProtection",
  },
  energyProtection: {
    name: "Cloud Fabric",
    effect: "Energy Protection",
    basic: [{ itemName: "Wyvern Talisman", quantity: 20 }],
    intricate: [
      { itemName: "Wyvern Talisman", quantity: 20 },
      { itemName: "Crawler Head Plating", quantity: 15 },
    ],
    powerful: [
      { itemName: "Wyvern Talisman", quantity: 20 },
      { itemName: "Crawler Head Plating", quantity: 15 },
      { itemName: "Wyrm Scale", quantity: 10 },
    ],
    icon: "energyProtection",
  },
  holyProtection: {
    name: "Demon Presence",
    effect: "Holy Protection",
    basic: [{ itemName: "Cultish Robe", quantity: 25 }],
    intricate: [
      { itemName: "Cultish Robe", quantity: 25 },
      { itemName: "Cultish Mask", quantity: 25 },
    ],
    powerful: [
      { itemName: "Cultish Robe", quantity: 25 },
      { itemName: "Cultish Mask", quantity: 25 },
      { itemName: "Hellspawn Tail", quantity: 20 },
    ],
    icon: "holyProtection",
  },
  iceProtection: {
    name: "Quara Scale",
    effect: "Ice Protection",
    basic: [{ itemName: "Winter Wolf Fur", quantity: 25 }],
    intricate: [
      { itemName: "Winter Wolf Fur", quantity: 25 },
      { itemName: "Thick Fur", quantity: 15 },
    ],
    powerful: [
      { itemName: "Winter Wolf Fur", quantity: 25 },
      { itemName: "Thick Fur", quantity: 15 },
      { itemName: "Deepling Warts", quantity: 10 },
    ],
    icon: "iceProtection",
  },
  earthProtection: {
    name: "Snake Skin",
    effect: "Earth Protection",
    basic: [{ itemName: "Piece of Swampling Wood", quantity: 25 }],
    intricate: [
      { itemName: "Piece of Swampling Wood", quantity: 25 },
      { itemName: "Snake Skin", quantity: 20 },
    ],
    powerful: [
      { itemName: "Piece of Swampling Wood", quantity: 25 },
      { itemName: "Snake Skin", quantity: 20 },
      { itemName: "Brimstone Fangs", quantity: 10 },
    ],
    icon: "earthProtection",
  },
  fireProtection: {
    name: "Dragon Hide",
    effect: "Fire Protection",
    basic: [{ itemName: "Green Dragon Leather", quantity: 20 }],
    intricate: [
      { itemName: "Green Dragon Leather", quantity: 20 },
      { itemName: "Blazing Bone", quantity: 10 },
    ],
    powerful: [
      { itemName: "Green Dragon Leather", quantity: 20 },
      { itemName: "Blazing Bone", quantity: 10 },
      { itemName: "Draken Sulphur", quantity: 5 },
    ],
    icon: "fireProtection",
  },
  lifeLeech: {
    name: "Vampirism",
    effect: "Life Leech",
    basic: [{ itemName: "Vampire Teeth", quantity: 25 }],
    intricate: [
      { itemName: "Vampire Teeth", quantity: 25 },
      { itemName: "Bloody Pincers", quantity: 15 },
    ],
    powerful: [
      { itemName: "Vampire Teeth", quantity: 25 },
      { itemName: "Bloody Pincers", quantity: 15 },
      { itemName: "Piece of Dead Brain", quantity: 5 },
    ],
    icon: "lifeLeech",
  },
  velocityIncrease: {
    name: "Swiftness",
    effect: "Velocity Increase",
    basic: [{ itemName: "Damselfly Wing", quantity: 15 }],
    intricate: [
      { itemName: "Damselfly Wing", quantity: 15 },
      { itemName: "Compass", quantity: 25 },
    ],
    powerful: [
      { itemName: "Damselfly Wing", quantity: 15 },
      { itemName: "Compass", quantity: 25 },
      { itemName: "Waspoid Wing", quantity: 20 },
    ],
    icon: "velocityIncrease",
  },
  paralysisRemoval: {
    name: "Vibrancy",
    effect: "Paralysis Removal",
    basic: [{ itemName: "Wereboar Hooves", quantity: 20 }],
    intricate: [
      { itemName: "Wereboar Hooves", quantity: 20 },
      { itemName: "Crystallized Anger", quantity: 15 },
    ],
    powerful: [
      { itemName: "Wereboar Hooves", quantity: 20 },
      { itemName: "Crystallized Anger", quantity: 15 },
      { itemName: "Quill", quantity: 5 },
    ],
    icon: "paralysisRemoval",
  },
  distanceSkill: {
    name: "Precision",
    effect: "Distance Skill",
    basic: [{ itemName: "Elven Scouting Glass", quantity: 25 }],
    intricate: [
      { itemName: "Elven Scouting Glass", quantity: 25 },
      { itemName: "Elven Hoof", quantity: 20 },
    ],
    powerful: [
      { itemName: "Elven Scouting Glass", quantity: 25 },
      { itemName: "Elven Hoof", quantity: 20 },
      { itemName: "Metal Spike", quantity: 10 },
    ],
    icon: "distanceSkill",
  },
  deathDamage: {
    name: "Reap",
    effect: "Death Damage",
    basic: [{ itemName: "Pile of Grave Earth", quantity: 25 }],
    intricate: [
      { itemName: "Pile of Grave Earth", quantity: 25 },
      { itemName: "Demonic Skeletal Hand", quantity: 20 },
    ],
    powerful: [
      { itemName: "Pile of Grave Earth", quantity: 25 },
      { itemName: "Demonic Skeletal Hand", quantity: 20 },
      { itemName: "Petrified Scream", quantity: 5 },
    ],
    icon: "deathDamage",
  },
  earthDamage: {
    name: "Venom",
    effect: "Earth Damage",
    basic: [{ itemName: "Swamp Grass", quantity: 25 }],
    intricate: [
      { itemName: "Swamp Grass", quantity: 25 },
      { itemName: "Poisonous Slime", quantity: 20 },
    ],
    powerful: [
      { itemName: "Swamp Grass", quantity: 25 },
      { itemName: "Poisonous Slime", quantity: 20 },
      { itemName: "Slime Heart", quantity: 2 },
    ],
    icon: "earthDamage",
  },
  energyDamage: {
    name: "Electrify",
    effect: "Energy Damage",
    basic: [{ itemName: "Rorc Feather", quantity: 25 }],
    intricate: [
      { itemName: "Rorc Feather", quantity: 25 },
      { itemName: "Peacock Feather Fan", quantity: 5 },
    ],
    powerful: [
      { itemName: "Rorc Feather", quantity: 25 },
      { itemName: "Peacock Feather Fan", quantity: 5 },
      { itemName: "Energy Vein", quantity: 1 },
    ],
    icon: "energyDamage",
  },
  fireDamage: {
    name: "Scorch",
    effect: "Fire Damage",
    basic: [{ itemName: "Fiery Heart", quantity: 25 }],
    intricate: [
      { itemName: "Fiery Heart", quantity: 25 },
      { itemName: "Green Dragon Scale", quantity: 5 },
    ],
    powerful: [
      { itemName: "Fiery Heart", quantity: 25 },
      { itemName: "Green Dragon Scale", quantity: 5 },
      { itemName: "Demon Horn", quantity: 5 },
    ],
    icon: "fireDamage",
  },
  iceDamage: {
    name: "Frost",
    effect: "Ice Damage",
    basic: [{ itemName: "Frosty Heart", quantity: 25 }],
    intricate: [
      { itemName: "Frosty Heart", quantity: 25 },
      { itemName: "Seacrest Hair", quantity: 10 },
    ],
    powerful: [
      { itemName: "Frosty Heart", quantity: 25 },
      { itemName: "Seacrest Hair", quantity: 10 },
      { itemName: "Polar Bear Paw", quantity: 5 },
    ],
    icon: "iceDamage",
  },
  manaLeech: {
    name: "Void",
    effect: "Mana Leech",
    basic: [{ itemName: "Rope Belt", quantity: 25 }],
    intricate: [
      { itemName: "Rope Belt", quantity: 25 },
      { itemName: "Silencer Claws", quantity: 25 },
    ],
    powerful: [
      { itemName: "Rope Belt", quantity: 25 },
      { itemName: "Silencer Claws", quantity: 25 },
      { itemName: "Some Grimeleech Wings", quantity: 5 },
    ],
    icon: "manaLeech",
  },
  criticalDamage: {
    name: "Strike",
    effect: "Critical Damage",
    basic: [{ itemName: "Protective Charm", quantity: 20 }],
    intricate: [
      { itemName: "Protective Charm", quantity: 20 },
      { itemName: "Sabretooth", quantity: 25 },
    ],
    powerful: [
      { itemName: "Protective Charm", quantity: 20 },
      { itemName: "Sabretooth", quantity: 25 },
      { itemName: "Vexclaw Talon", quantity: 5 },
    ],
    icon: "criticalDamage",
  },
  axeSkill: {
    name: "Chop",
    effect: "Axe Skill",
    basic: [{ itemName: "Orc Tooth", quantity: 20 }],
    intricate: [
      { itemName: "Orc Tooth", quantity: 20 },
      { itemName: "Battle Stone", quantity: 25 },
    ],
    powerful: [
      { itemName: "Orc Tooth", quantity: 20 },
      { itemName: "Battle Stone", quantity: 25 },
      { itemName: "Moohtant Horn", quantity: 20 },
    ],
    icon: "axeSkill",
  },
  clubSkill: {
    name: "Bash",
    effect: "Club Skill",
    basic: [{ itemName: "Cyclops Toe", quantity: 20 }],
    intricate: [
      { itemName: "Cyclops Toe", quantity: 20 },
      { itemName: "Ogre Nose Ring", quantity: 15 },
    ],
    powerful: [
      { itemName: "Cyclops Toe", quantity: 20 },
      { itemName: "Ogre Nose Ring", quantity: 15 },
      { itemName: "Warmaster's Wristguards", quantity: 10 },
    ],
    icon: "clubSkill",
  },
  fistSkill: {
    name: "Punch",
    effect: "Fist Fighting Skill",
    basic: [{ itemName: "Ghostly Tissue", quantity: 20 }],
    intricate: [
      { itemName: "Ghostly Tissue", quantity: 20 },
      { itemName: "Mantassin Tail", quantity: 25 },
    ],
    powerful: [
      { itemName: "Ghostly Tissue", quantity: 20 },
      { itemName: "Mantassin Tail", quantity: 25 },
      { itemName: "Gold-Brocaded Cloth", quantity: 10 },
    ],
    icon: "fistSkill",
  },
  swordSkill: {
    name: "Slash",
    effect: "Sword Skill",
    basic: [{ itemName: "Lion's Mane", quantity: 25 }],
    intricate: [
      { itemName: "Lion's Mane", quantity: 25 },
      { itemName: "Mooh'tah Shell", quantity: 25 },
    ],
    powerful: [
      { itemName: "Lion's Mane", quantity: 25 },
      { itemName: "Mooh'tah Shell", quantity: 25 },
      { itemName: "War Crystal", quantity: 5 },
    ],
    icon: "swordSkill",
  },
  shieldingSkill: {
    name: "Blockade",
    effect: "Shielding Skill",
    basic: [{ itemName: "Piece of Scarab Shell", quantity: 20 }],
    intricate: [
      { itemName: "Piece of Scarab Shell", quantity: 20 },
      { itemName: "Brimstone Shell", quantity: 25 },
    ],
    powerful: [
      { itemName: "Piece of Scarab Shell", quantity: 20 },
      { itemName: "Brimstone Shell", quantity: 25 },
      { itemName: "Frazzle Skin", quantity: 25 },
    ],
    icon: "shieldingSkill",
  },
  magicLevel: {
    name: "Ephifany",
    effect: "Magic Level",
    basic: [{ itemName: "Elvish Talisman", quantity: 25 }],
    intricate: [
      { itemName: "Elvish Talisman", quantity: 25 },
      { itemName: "Broken Shamanic Staff", quantity: 15 },
    ],
    powerful: [
      { itemName: "Elvish Talisman", quantity: 25 },
      { itemName: "Broken Shamanic Staff", quantity: 15 },
      { itemName: "Strand of Medusa Hair", quantity: 15 },
    ],
    icon: "magicLevel",
  },
  capacityIncrease: {
    name: "Featherweight",
    effect: "Capacity Increase",
    basic: [{ itemName: "Fairy Wings", quantity: 20 }],
    intricate: [
      { itemName: "Fairy Wings", quantity: 20 },
      { itemName: "Little Bowl of Myrrh", quantity: 10 },
    ],
    powerful: [
      { itemName: "Fairy Wings", quantity: 20 },
      { itemName: "Little Bowl of Myrrh", quantity: 10 },
      { itemName: "Goosebump Leather", quantity: 5 },
    ],
    icon: "capacityIncrease",
  },
};
